In [ ]:
a=10
print(a)

10

In [ ]:
b=45
b

45

In [ ]:
a=10
b=35
a+b

45

In [ ]:
s=[10,20,30,40,50]
s
r=(10,20,30,'sri')
r

(10, 20, 30, 'sri')

In [ ]:
import numpy as np
data=np.array(s)
s

[10, 20, 30, 40, 50]

In [ ]:
import numpy as n
raw=n.array(s)
s

[10, 20, 30, 40, 50]

In [ ]:
print(np.max(s))

50

In [ ]:
print(np.min(s))

10

In [ ]:
a=np.zeros([4,4])
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
c=np.ones([3,3])
c

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
v=np.random.rand(1,10)
v

array([[0.96071538, 0.10813768, 0.92646579, 0.91371127, 0.63196792,
        0.57489571, 0.84793947, 0.29212778, 0.40571046, 0.50205951]])

In [ ]:
n=np.random.rand(1,3)
n

array([[0.48973327, 0.08794586, 0.13340896]])

In [ ]:
a=np.array([11,22,33,4,5,6,7,8,9,2,4,6,1,22,3,4])
d=np.reshape(a,(2,8))
d

array([[11, 22, 33,  4,  5,  6,  7,  8],
       [ 9,  2,  4,  6,  1, 22,  3,  4]])

In [ ]:
s=np.array([10,20,3,0,40,50,60,70,80,90,100,45]),
r=np.reshape(s,(3,4))
r

array([[ 10,  20,   3,   0],
       [ 40,  50,  60,  70],
       [ 80,  90, 100,  45]])

In [ ]:
b=np.arange(15).reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
m=np.arange(45).reshape(5,9)
m

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a+b

array([5, 7, 9])

In [ ]:
s=np.array([10,20,30])
r=np.array([35,25,15])
s+r

array([45, 45, 45])

In [ ]:
a = np.array([10,20,3])
b = np.array([4,5,6])
a-b

array([ 6, 15, -3])

In [ ]:
a = np.array([10,20,3])
b = np.array([4,5,6])
a*b

array([ 40, 100,  18])

In [ ]:
a = np.array([10,20,3])
b = np.array([4,5,6])
a/b

array([2.5, 4. , 0.5])

In [ ]:
a = np.array([10,20,3])
b = np.array([4,5,6])
a%b

array([2, 0, 3])

In [ ]:
a = np.array([[1,2,3],[6,7,8]])
b = np.array([[4,5],
              [8,4],
              [6,5]])
c=np.dot(a,b)
c

array([[ 38,  28],
       [128,  98]])

In [ ]:
mat = np.array([[1,2,3],[4,5,6]])
print(mat.T)

[[1 4]
 [2 5]
 [3 6]]

In [ ]:
m=np.array([[10,20,30],[40,52,60]])
print(m.T)

[[10 40]
 [20 52]
 [30 60]]

In [ ]:
arr = np.array([5,2,8,1,9])
print(np.sort(arr))

[1 2 5 8 9]

In [ ]:
S=np.array([10,20,5,45,30,15])
print(np.sort(S))

[ 5 10 15 20 30 45]

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b)))

[1 2 3 4 5 6]

In [ ]:
x=np.array([10,20,30])
y=np.array([40,50,60])
print(np.concatenate((x,y)))

[10 20 30 40 50 60]

In [ ]:
arr = np.array([1,2,2,3,4,4,5])
d=np.unique(arr)
d

array([1, 2, 3, 4, 5])

In [ ]:
x=np.array([10,20,10,30,20,45,30])
print(np.unique(x))

[10 20 30 45]

In [ ]:



print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [ ]:
print(np.eye(6,6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

In [ ]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]

In [ ]:
s=np.linspace(1,20,10)
s

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [78]:
from google.colab import files
uploaded = files.upload()

Saving ipl_data.csv to ipl_data.csv

In [80]:
import pandas as pd
df = pd.read_csv("ipl_data.csv")
print(df.head())

   mid        date                  venue               bat_team  \
0    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
1    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
2    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
3    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders
4    1  2008-04-18  M Chinnaswamy Stadium  Kolkata Knight Riders

                     bowl_team      batsman   bowler  runs  wickets  overs  \
0  Royal Challengers Bangalore   SC Ganguly  P Kumar     1        0    0.1
1  Royal Challengers Bangalore  BB McCullum  P Kumar     1        0    0.2
2  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.2
3  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.3
4  Royal Challengers Bangalore  BB McCullum  P Kumar     2        0    0.4

   runs_last_5  wickets_last_5  striker  non-striker  total
0            1               0        0            0    222
1            1               0        0            0    222
2            2               0        0            0    222
3            2               0        0            0    222
4            2               0        0            0    222

In [83]:
df["date"]

0        2008-04-18
1        2008-04-18
2        2008-04-18
3        2008-04-18
4        2008-04-18
            ...
76009    2017-05-21
76010    2017-05-21
76011    2017-05-21
76012    2017-05-21
76013    2017-05-21
Name: date, Length: 76014, dtype: object

In [84]:
df["venue"]

0                            M Chinnaswamy Stadium
1                            M Chinnaswamy Stadium
2                            M Chinnaswamy Stadium
3                            M Chinnaswamy Stadium
4                            M Chinnaswamy Stadium
                           ...
76009    Rajiv Gandhi International Stadium, Uppal
76010    Rajiv Gandhi International Stadium, Uppal
76011    Rajiv Gandhi International Stadium, Uppal
76012    Rajiv Gandhi International Stadium, Uppal
76013    Rajiv Gandhi International Stadium, Uppal
Name: venue, Length: 76014, dtype: object

In [85]:
df[df["venue"] == "M Chinnaswamy Stadium"]

,mid,date,venue,bat_team,bowl_team,batsman,bowler,runs,wickets,overs,runs_last_5,wickets_last_5,striker,non-striker,total
0,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,SC Ganguly,P Kumar,1,0,0.1,1,0,0,0,222
1,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,1,0,0.2,1,0,0,0,222
2,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.2,2,0,0,0,222
3,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.3,2,0,0,0,222
4,1,2008-04-18,M Chinnaswamy Stadium,Kolkata Knight Riders,Royal Challengers Bangalore,BB McCullum,P Kumar,2,0,0.4,2,0,0,0,222
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75884,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,UT Yadav,SL Malinga,106,9,18.1,29,4,4,1,107
75885,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,UT Yadav,SL Malinga,107,9,18.2,29,4,4,2,107
75886,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,9,18.3,28,4,4,2,107
75887,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,9,18.4,24,4,4,2,107
75888,616,2017-05-19,M Chinnaswamy Stadium,Kolkata Knight Riders,Mumbai Indians,AS Rajpoot,SL Malinga,107,10,18.5,23,5,4,2,107

In [86]:
df["runs_last_5"].sum()

np.int64(2524914)